version: '1.0'
name: MainScan-20230524
displayName: MainScan
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-e5e59d6d
    displayName: 未命名
    strategy: fast
    trigger: auto
    executor: []
    steps:
      - step: sc@opensca
        name: open_sca
        displayName: OpenSCA 开源组件检测
        detectPath: ./
        notify: []
        strategy:
          retry: '0'
